### ISSUE TITLE
Make sure that it is easy for someone to 'git clone' the oh-missions repo and get it running on their system ** Note that we should have someone test this, to make sure it actually is easy

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-missions-oppia-beta#8] opened 2013-09-30 18:13 UTC

**Comment by paulproteus** [comment] 2013-09-30 18:20
To have this be great, we probably want documentation that lives in oh-missions.readthedocs.org.

**Comment by sunu** [comment] 2013-10-23 18:34
Waiting for positive user testing report from @mandarg to  continue.

**Comment by mandarg** [comment] 2013-10-24 05:29
Runs correctly and can see the Oppia app at localhost:8181 on OSX 10.6.8 and Ubuntu 12.04, but with the same minor issue in both: If `coverage` is not installed, the script will install `coverage`, but then do nothing. You have to re-run it, and then it will work correctly. 

You can probably test this on your systems by doing a `sudo pip uninstall coverage` and running the `start.sh` script (I'm assuming no `virtualenv`s since they aren't mentioned anywhere).

There are a couple other things, like mentioning something like "Open [http://localhost:8181](http://localhost:8181) in your browser" in case the user isn't using Chrome, and mentioning in the README that Linux is assumed, though it has been kinda tested on Snow Leopard. I can cover those in a pull request (unless you people are in a hurry to ship).

**Comment by mandarg** [comment] 2013-10-24 05:33
Example of problem mentioned above (Ubuntu 12.04):

```
Checking if coverage is installed on the system
Coverage is NOT installed
Installing coverage
--2013-10-24 01:19:10--  http://pypi.python.org/packages/source/c/coverage/coverage-3.6.tar.gz
Resolving pypi.python.org (pypi.python.org)... 199.27.73.184, 199.27.73.185
Connecting to pypi.python.org (pypi.python.org)|199.27.73.184|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.python.org/packages/source/c/coverage/coverage-3.6.tar.gz [following]
--2013-10-24 01:19:10--  https://pypi.python.org/packages/source/c/coverage/coverage-3.6.tar.gz
Connecting to pypi.python.org (pypi.python.org)|199.27.73.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 232067 (227K) [application/x-gzip]
Saving to: `coverage.tar.gz'

100%[==========================================>] 232,067      548K/s   in 0.4s    

.
. (misc install stuff)
.
.
Adding coverage 3.6 to easy-install.pth file
Installing coverage2 script to /usr/local/bin
Installing coverage-2.7 script to /usr/local/bin
Installing coverage script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/coverage-3.6-py2.7-linux-x86_64.egg
Processing dependencies for coverage==3.6
Finished processing dependencies for coverage==3.6
No file to run: './core/tests/gae_suite.py'
Adding coverage 3.6 to easy-install.pth file
Installing coverage2 script to /usr/local/bin
Installing coverage-2.7 script to /usr/local/bin
Installing coverage script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/coverage-3.6-py2.7-linux-x86_64.egg
Processing dependencies for coverage==3.6
Finished processing dependencies for coverage==3.6
No file to run: './core/tests/gae_suite.py'
```

.

**Comment by sunu** [comment] 2013-10-24 06:49
Hi @mandarg !
Thanks for the detailed bug reporting :) I pushed https://github.com/openhatch/oh-missions-oppia-beta/commit/b526ce52e94409bd9b545f5b60f2ac9ea38e4626 fixing the coverage issue.
Could you confirm for us that the issue is indeed fixed now?

**Comment by paulproteus** [comment] 2013-10-25 18:39
Hmm... why is mandarg executing things as root? That seems like bad news.

**Comment by mandarg** [comment] 2013-10-25 18:55
On my stock ubuntu install (python 2.7 and pip both installed from the package archives IIRC), python modules are installed to `/usr/local/lib/python2.7/dist-packages`, which needs `sudo` to modify. Please note that I am not using a virtualenv, or python installed from source.

I need `sudo` for running `pip install` or `pip uninstall` as well. 

If you think this is an artifact of where python is installed on my system, or something else?

**Comment by mandarg** [comment] 2013-10-25 18:57
By the way, from my side, the script appears to be working perfectly now, both on Ubuntu and OSX 10.6.8.

**Comment by sunu** [comment] 2013-10-25 19:00
@mandarg What @paulproteus meant is we should not force you to use root. That is a bad thing for us to do in the script.
Thanks for the feedback :)

**Closed as completed** 2013-10-29 14:01 UTC
